#!/usr/bin/expect
set timeout 2400 
set total [llength $argv]
#172.17.254.152 server以下線
#spawn sftp ams@172.17.254.152
#expect "password:"

#send "smasmasma@3F\r"
#expect "sftp> "
#send "cd upload\r"

#set count  0

#while {$count < $total } {
#set filename [lindex $argv $count];
#expect "sftp> "
#send "put $filename\r"

#set count [expr $count+1];
#}


#expect "sftp> "
#send "quit\r"




spawn sftp ams@172.17.254.180
expect "password:"
send "1234QWERasdf\r"
expect "sftp> "
send "cd upload\r"

set count  0

while {$count < $total } {
set filename [lindex $argv $count];
expect "sftp> "
send "put $filename\r"

set count [expr $count+1];
}


expect "sftp> "
send "quit\r"
