<?php
	header("Content-Type:text/html; charset=utf-8");
	
	require_once dirname(__FILE__).'/../tool/MyLogger.php';
	require_once dirname(__FILE__).'/../tool/MyDB.php';
	require_once dirname(__FILE__).'/../tool/FTP.php';
	require_once '../tool/OracleDB.php';
	$oracleDB=new OracleDB(Config::OMP_N_ORACLE_DB_USER,Config::OMP_N_ORACLE_DB_PASSWORD,Config::OMP_N_ORACLE_DB_CONN_STR);
	/*$sql='
				SELECT
					CBAS.BAKADSCHD_TRANSACTION_ID,
					CBA.BAKAD_NAME,
					CBA.SD_VODCNT_RECID,
					CBA.HD_VODCNT_RECID,
					OVCSD.VODCNT_TITLE AS SD_VODCNT_TITLE,
					OVCHD.VODCNT_TITLE AS HD_VODCNT_TITLE,
					CBA.BAKAD_DISPLAY_MAX,
					LK.LINK_TYPE,
					LK.LINK_CHAN_RECID,
					LK.LINK_CAT_RECID,
					LK.LINK_VODCNT_RECID,
					LK.LINK_SRVC_RECID,
					CS.SER_CODE,
					to_char(CBAS.BAKADSCHD_START_DATE,\'YYYY/MM/DD HH24:MI\') BAKADSCHD_START_DATE,
					to_char(CBAS.BAKADSCHD_END_DATE,\'YYYY/MM/DD HH24:MI\') BAKADSCHD_END_DATE,
					CBAS.BAKADSCHD_ASSIGN_START_TIME,
					CBAS.BAKADSCHD_ASSIGN_END_TIME,
					CBAS.BAKADSCHD_DISPLAY_SEQUENCE,
					CBAS.BAKADSCHD_DISPLAY_MAX,
					CAS.TRANSACTION_ID,
					CBAS.BAKADSCHD_STATUS,
					CSTB.BNR_SEQUENCE
				FROM CS_BARKER_AD_SCHEDULE CBAS
				INNER JOIN CS_SERVICE CS ON CBAS.SER_RECID=CS.SER_RECID
				INNER JOIN CS_BARKER_AD CBA ON CBA.BAKAD_RECID=CBAS.BAKAD_RECID
				INNER JOIN CS_LINK LK ON CBA.LINK_RECID=LK.LINK_RECID
				LEFT OUTER JOIN CS_GROUP_AD CGA ON CBAS.BAKADSCHD_RECID=CGA.BAKADSCHD_RECID
				LEFT OUTER JOIN CS_AD_SCHEDULE CAS ON CAS.AD_SCHDID=CGA.AD_SCHDID
				LEFT OUTER JOIN CS_AD CA ON CAS.AD_RECID=CA.AD_RECID
				LEFT OUTER JOIN CS_SER_TMP_BNR CSTB ON CSTB.BNR_RECID=CA.BNR_RECID
				LEFT OUTER JOIN OVA_VOD_CONTENT OVCSD ON CBA.SD_VODCNT_RECID=OVCSD.VODCNT_RECID
				LEFT OUTER JOIN OVA_VOD_CONTENT OVCHD ON CBA.HD_VODCNT_RECID=OVCHD.VODCNT_RECID
				WHERE
					CBAS.BAKADSCHD_TRANSACTION_ID=:TID
				ORDER BY
					CBAS.BAKADSCHD_START_DATE,
					CBAS.BAKADSCHD_TRANSACTION_ID
			';*/
			$sql='
				SELECT
					CBAS.BAKADSCHD_TRANSACTION_ID,
					CSTB.BNR_SEQUENCE
				FROM CS_BARKER_AD_SCHEDULE CBAS
				INNER JOIN CS_BARKER_AD CBA ON CBA.BAKAD_RECID=CBAS.BAKAD_RECID
				INNER JOIN CS_GROUP_AD CGA ON CBAS.BAKADSCHD_RECID=CGA.BAKADSCHD_RECID
				INNER JOIN CS_AD_SCHEDULE CAS ON CAS.AD_SCHDID=CGA.AD_SCHDID
				LEFT OUTER JOIN CS_SER_TMP_BNR CSTB ON CSTB.CS_STB_RECID=CAS.CS_STB_RECID
				WHERE
					CBAS.BAKADSCHD_TRANSACTION_ID=:TID
				ORDER BY
					CSTB.BNR_SEQUENCE
			';
			$vars=array(
				array('bv_name'=>':TID','variable'=>78)
			);
			$result=$oracleDB->getResultArray($sql,$vars);
			print_r($result);
			exit;	
?>